properties([
    parameters([
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Select the deployment environment'),
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag or application version to deploy'),
    ])
])


pipeline {
    agent any

    environment {
        SERVICE_NAME = 'sample-service-node'
        KUBECONFIG = '/var/jenkins_home/.kube/config'
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Checking out source code"
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    echo "Installing dependencies"
                    npm install || echo "npm install failed, or package.json is missing..."
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    echo "Running tests"
                    npm test || echo "Test failed or not defined, adjust as needed..."
                '''
            }
        }

        stage('Build artifact') {
            steps {
                sh '''
                    echo "Building application for environment: ${ENVIRONMENT} with IMAGE_TAG: ${IMAGE_TAG}"
                    npm run build || echo "Build failed or not defined, adjust as needed..."
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    echo "Starting deploy"
                    echo "Deploying service '${SERVICE_NAME}' to environment '${ENVIRONMENT}' with tag '${IMAGE_TAG}'"
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh """
                    echo '>>> Deploying to Kubernetes namespace: ${ENVIRONMENT}'
                    echo '>>> Kube context:'
                    kubectl config current-context

                    sed -i 's/<IMAGE_TAG>/${IMAGE_TAG}/g' pipelines/sample-pipeline/k8s/deployment.yaml

                    echo '>>> Applying manifests...'
                    kubectl apply -f pipelines/sample-pipeline/k8s -n ${ENVIRONMENT}

                    echo '>>> Waiting for rollout...'
                    kubectl rollout status deployment/sample-service -n ${ENVIRONMENT}

                    echo '>>> Listing Pods'
                    kubectl get pods -n ${ENVIRONMENT}

                    echo '>>> Listing Services'
                    kubectl get svc -n ${ENVIRONMENT}
                """
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully for environment: ${ENVIRONMENT} with tag: ${IMAGE_TAG}"
        }
        failure {
            echo "Pipeline failed for environment: ${ENVIRONMENT} with tag: ${IMAGE_TAG}"
        }
    }
}
